# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc_code', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('branch_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
